name: trigger

on:
  workflow_dispatch:

env:
  EVENT_TYPE: btp-metadata-update
  TARGET_OWNER: lechnerc77
  TARGET_REPO: btp-setup-automator

jobs:
  update-metadata-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Send event to dependent repositories
        uses: actions/github-script@v6
        with:
          result-encoding: string
          retry-exempt-status-codes: 400,401
          retries: 3
          github-token: ${{ secrets.BTPSA_EVENT_TOKEN }}
          script: |
            github.rest.repos.createDispatchEvent({
              owner: "lechnerc77",
              repo: "btp-setup-automator",
              event_type: "btp-setup-automator"
            })      